#!/bin/bash

# mounts a filesystem from an encrypted partition

name=$1

usage() {
	cat <<- EOF
	usage:   $0 device-name
	example: $0 voyager
	EOF
}

if [[ -z $name ]]; then
  echo "Error: missing device-name" >&2
  usage >&2
  exit 1
fi

/bin/grep -q $name /etc/mtab && {
  echo "Error: $name seems to be mounted already"
  exit 1
} >&2

/usr/bin/test -L /dev/$name || {
  echo "Error: /dev/$name is not a symlink"
  exit 1
} >&2

/usr/bin/test -d /media/$name || {
  # mountpoint should be created by /etc/udev/rules/75-external-disk.rules
  echo "Error: /media/$name is not a directory"
  exit 1
} >&2

read -sp "Crypt passphrase: " phrase
echo "" >&2
if [ "x" != "x$phrase" ]; then
	echo $phrase | cryptsetup create $name /dev/$name
	/bin/mount /dev/mapper/$name /media/$name
fi
